export const CREATE_EMPLOYEE_MODAL = 'CREATE_EMPLOYEE_MODAL';
export const UPDATE_EMPLOYEE_MODAL = 'UPDATE_EMPLOYEE_MODAL';
export const CREATE_PERFORMANCE_REVIEW_MODAL = 'CREATE_PERFORMANCE_REVIEW_MODAL';
export const UPDATE_PERFORMANCE_REVIEW_MODAL = 'UPDATE_PERFORMANCE_REVIEW_MODAL';
